README.md Add about Ubuntu 24
CMake Error at qtbase/cmake/QtBuildInformation.cmake:559 (message):
  Feature "wayland": Forcing to "ON" breaks its condition:

      TARGET Wayland::Client

  Condition values dump:

      TARGET Wayland::Client not found

Call Stack (most recent call first):
  qtbase/cmake/QtFeature.cmake:831 (qt_configure_add_report_error)
  qtbase/cmake/QtFeature.cmake:968 (qt_feature_check_and_save_internal_value)
  qtbase/cmake/QtFeature.cmake:1249 (qt_evaluate_feature)
  qtbase/cmake/QtFeature.cmake:1213 (qt_feature_module_end)
  qtbase/src/CMakeLists.txt:13 (qt_feature_evaluate_features)



-- Configuration summary has been written to /home/q/Ubuntu_Wayland_Build_Qt_widgets/Qt_themself/build_host_powerfull/config.summary

ERROR: Feature "wayland": Forcing to "ON" breaks its condition:
    TARGET Wayland::Client
Condition values dump:
    TARGET Wayland::Client not found


CMake Error at qtbase/cmake/QtBuildInformation.cmake:245 (message):
  Check the configuration messages for an error that has occurred.
Call Stack (most recent call first):
  qtbase/cmake/QtBuildInformation.cmake:64 (qt_configure_print_summary)
  qtbase/cmake/QtBaseTopLevelHelpers.cmake:114 (qt_print_feature_summary)
  qtbase/cmake/QtBaseTopLevelHelpers.cmake:93 (qt_internal_print_top_level_info)
  CMakeLists.txt:124 (qt_internal_top_level_end)


-- Configuring incomplete, errors occurred!
CMake Error at /home/q/Ubuntu_Wayland_Build_Qt_widgets/Qt_themself/qt5/qtbase/cmake/QtProcessConfigureArgs.cmake:1584 (message):
  CMake exited with code 1.


CMake Error at /home/q/Ubuntu_Wayland_Build_Qt_widgets/Qt_themself/qt5/cmake/QtIRProcessHelpers.cmake:173 (message):
  /home/q/Ubuntu_Wayland_Build_Qt_widgets/Qt_themself/qt5/qtbase/configure
  -top-level -release -static -opensource -nomake examples -nomake tests
  -confirm-license -ltcg -disable-deprecated-up-to 0x061100 -no-ssl -prefix
  ../build_artifacts_host_powerfull -system-freetype -skip
  webengine,qtwayland,qtdoc,qtgraphicaleffects,qtqa,qttranslations,qtvirtualkeyboard,qtquicktimeline,qtquick3d,qt3d,qtrepotools,qttools,qtimageformats,qtnetworkauth,qtwebsockets,qtactiveqt,qtmacextras,winextras,qtmultimedia,qtgamepad,qtserialbus,qtspeech,qtsensors,qtlanguageserver,qtdeclarative,qtlocation,qtsvg,qtshadertools,qtserialport,qtcharts
  -- -GNinja -DCMAKE_TOOLCHAIN_FILE=../toolchain_host_powerfull.cmake exited
  with status: 1

Call Stack (most recent call first):
  /home/q/Ubuntu_Wayland_Build_Qt_widgets/Qt_themself/qt5/cmake/QtTopLevelHelpers.cmake:35 (qt_ir_execute_process_and_log_and_handle_error)
  /home/q/Ubuntu_Wayland_Build_Qt_widgets/Qt_themself/qt5/cmake/QtTopLevelHelpers.cmake:57 (qt_tl_run_toplevel_configure)
  /home/q/Ubuntu_Wayland_Build_Qt_widgets/Qt_themself/qt5/cmake/QtTopLevelConfigureScript.cmake:16 (qt_tl_run_main_script